# Site settings
title: Learn TurtleBot and ROS
email: mwsilliman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An open source getting started guide for web, mobile and maker developers interested in robotics.
baseurl: "/turtlebot" # the subpath of your site, e.g. /blog/
url: "http://0.0.0.0:4000/turtlebot" # the base hostname & protocol for your site
github_username:  markwsilliman

# Build settings
markdown: kramdown
permalink: pretty